apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.example.sbose.com
spec:
  group: example.sbose.com
  names:
    kind: Example
    listKind: ExampleList
    plural: examples
    singular: example
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Example is the Schema for the examples API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ExampleSpec defines the desired state of Example
            properties:
              testSubject:
                description: TestSubject is the resource that would be validated for
                  permissions.
                properties:
                  group:
                    type: string
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                  resource:
                    type: string
                  version:
                    type: string
                required:
                - group
                - resource
                - version
                type: object
              username:
                description: Username is the user on behalf of whom SAR checks need
                  to be done.
                type: string
            required:
            - testSubject
            - username
            type: object
          status:
            description: ExampleStatus defines the observed state of Example
            properties:
              allowed:
                type: boolean
            required:
            - allowed
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
